(function (factory) {
    if (typeof define === "function" && define.amd) {
        define([
            "./Utils"
        ], factory);
    } else {
        factory();
    }
}(function () {
    var TimeZoneMapping = {
        DisplayValues: [
            "(UTC-12:00) International Date Line West",
            "(UTC-11:00) Coordinated Universal Time-11",
            "(UTC-10:00) Aleutian Islands",
            "(UTC-10:00) Hawaii",
            "(UTC-09:30) Marquesas Islands",
            "(UTC-09:00) Alaska",
            "(UTC-09:00) Coordinated Universal Time-09",
            "(UTC-08:00) Baja California",
            "(UTC-08:00) Coordinated Universal Time-08",
            "(UTC-08:00) Pacific Time (US & Canada)",
            "(UTC-07:00) Arizona",
            "(UTC-07:00) Chihuahua, La Paz, Mazatlan",
            "(UTC-07:00) Mountain Time (US & Canada)",
            "(UTC-06:00) Central America",
            "(UTC-06:00) Central Time (US & Canada)",
            "(UTC-06:00) Easter Island",
            "(UTC-06:00) Guadalajara, Mexico City, Monterrey",
            "(UTC-06:00) Saskatchewan",
            "(UTC-05:00) Bogota, Lima, Quito, Rio Branco",
            "(UTC-05:00) Chetumal",
            "(UTC-05:00) Eastern Time (US & Canada)",
            "(UTC-05:00) Haiti",
            "(UTC-05:00) Havana",
            "(UTC-05:00) Indiana (East)",
            "(UTC-05:00) Turks and Caicos",
            "(UTC-04:00) Asuncion",
            "(UTC-04:00) Atlantic Time (Canada)",
            "(UTC-04:00) Caracas",
            "(UTC-04:00) Cuiaba",
            "(UTC-04:00) Georgetown, La Paz, Manaus, San Juan",
            "(UTC-04:00) Santiago",
            "(UTC-03:30) Newfoundland",
            "(UTC-03:00) Araguaina",
            "(UTC-03:00) Brasilia",
            "(UTC-03:00) Cayenne, Fortaleza",
            "(UTC-03:00) City of Buenos Aires",
            "(UTC-03:00) Greenland",
            "(UTC-03:00) Montevideo",
            "(UTC-03:00) Punta Arenas",
            "(UTC-03:00) Saint Pierre and Miquelon",
            "(UTC-03:00) Salvador",
            "(UTC-02:00) Coordinated Universal Time-02",
            "(UTC-01:00) Azores",
            "(UTC-01:00) Cabo Verde Is.",
            "(UTC) Coordinated Universal Time",
            "(UTC+00:00) Casablanca",
            "(UTC+00:00) Dublin, Edinburgh, Lisbon, London",
            "(UTC+00:00) Monrovia, Reykjavik",
            "(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna",
            "(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague",
            "(UTC+01:00) Brussels, Copenhagen, Madrid, Paris",
            "(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb",
            "(UTC+01:00) West Central Africa",
            "(UTC+02:00) Amman",
            "(UTC+02:00) Athens, Bucharest",
            "(UTC+02:00) Beirut",
            "(UTC+02:00) Cairo",
            "(UTC+02:00) Chisinau",
            "(UTC+02:00) Damascus",
            "(UTC+02:00) Gaza, Hebron",
            "(UTC+02:00) Harare, Pretoria",
            "(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius",
            "(UTC+02:00) Jerusalem",
            "(UTC+02:00) Kaliningrad",
            "(UTC+02:00) Khartoum",
            "(UTC+02:00) Tripoli",
            "(UTC+02:00) Windhoek",
            "(UTC+03:00) Baghdad",
            "(UTC+03:00) Istanbul",
            "(UTC+03:00) Kuwait, Riyadh",
            "(UTC+03:00) Minsk",
            "(UTC+03:00) Moscow, St. Petersburg, Volgograd",
            "(UTC+03:00) Nairobi",
            "(UTC+03:30) Tehran",
            "(UTC+04:00) Abu Dhabi, Muscat",
            "(UTC+04:00) Astrakhan, Ulyanovsk",
            "(UTC+04:00) Baku",
            "(UTC+04:00) Izhevsk, Samara",
            "(UTC+04:00) Port Louis",
            "(UTC+04:00) Saratov",
            "(UTC+04:00) Tbilisi",
            "(UTC+04:00) Yerevan",
            "(UTC+04:30) Kabul",
            "(UTC+05:00) Ashgabat, Tashkent",
            "(UTC+05:00) Ekaterinburg",
            "(UTC+05:00) Islamabad, Karachi",
            "(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi",
            "(UTC+05:30) Sri Jayawardenepura",
            "(UTC+05:45) Kathmandu",
            "(UTC+06:00) Astana",
            "(UTC+06:00) Dhaka",
            "(UTC+06:00) Omsk",
            "(UTC+06:30) Yangon (Rangoon)",
            "(UTC+07:00) Bangkok, Hanoi, Jakarta",
            "(UTC+07:00) Barnaul, Gorno-Altaysk",
            "(UTC+07:00) Hovd",
            "(UTC+07:00) Krasnoyarsk",
            "(UTC+07:00) Novosibirsk",
            "(UTC+07:00) Tomsk",
            "(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi",
            "(UTC+08:00) Irkutsk",
            "(UTC+08:00) Kuala Lumpur, Singapore",
            "(UTC+08:00) Perth",
            "(UTC+08:00) Taipei",
            "(UTC+08:00) Ulaanbaatar",
            "(UTC+08:30) Pyongyang",
            "(UTC+08:45) Eucla",
            "(UTC+09:00) Chita",
            "(UTC+09:00) Osaka, Sapporo, Tokyo",
            "(UTC+09:00) Seoul",
            "(UTC+09:00) Yakutsk",
            "(UTC+09:30) Adelaide",
            "(UTC+09:30) Darwin",
            "(UTC+10:00) Brisbane",
            "(UTC+10:00) Canberra, Melbourne, Sydney",
            "(UTC+10:00) Guam, Port Moresby",
            "(UTC+10:00) Hobart",
            "(UTC+10:00) Vladivostok",
            "(UTC+10:30) Lord Howe Island",
            "(UTC+11:00) Bougainville Island",
            "(UTC+11:00) Chokurdakh",
            "(UTC+11:00) Magadan",
            "(UTC+11:00) Norfolk Island",
            "(UTC+11:00) Sakhalin",
            "(UTC+11:00) Solomon Is., New Caledonia",
            "(UTC+12:00) Anadyr, Petropavlovsk-Kamchatsky",
            "(UTC+12:00) Auckland, Wellington",
            "(UTC+12:00) Coordinated Universal Time+12",
            "(UTC+12:00) Fiji",
            "(UTC+12:45) Chatham Islands",
            "(UTC+13:00) Coordinated Universal Time+13",
            "(UTC+13:00) Nuku'alofa",
            "(UTC+13:00) Samoa",
            "(UTC+14:00) Kiritimati Island"
        ],
        IanaValues: [
            ["Etc/GMT+12"],
            ["Etc/GMT+11", "Pacific/Pago_Pago", "Pacific/Niue", "Pacific/Midway"],
            ["America/Adak"],
            ["Pacific/Honolulu", "Pacific/Rarotonga", "Pacific/Tahiti", "Pacific/Johnston", "Etc/GMT+10"],
            ["Pacific/Marquesas"],
            ["America/Anchorage", "America/Juneau", "America/Metlakatla", "America/Nome", "America/Sitka", "America/Yakutat"],
            ["Etc/GMT+9", "Pacific/Gambier"],
            ["America/Tijuana", "America/Santa_Isabel"],
            ["Etc/GMT+8", "Pacific/Pitcairn"],
            ["America/Los_Angeles", "America/Vancouver", "America/Dawson", "America/Whitehorse", "PST8PDT"],
            ["America/Phoenix", "America/Dawson_Creek", "America/Creston", "America/Fort_Nelson", "America/Hermosillo", "Etc/GMT+7"],
            ["America/Chihuahua", "America/Mazatlan"],
            ["America/Denver", "America/Edmonton", "America/Cambridge_Bay", "America/Inuvik", "America/Yellowknife", "America/Ojinaga", "America/Boise", "MST7MDT"],
            ["America/Guatemala", "America/Belize", "America/Costa_Rica", "Pacific/Galapagos", "America/Tegucigalpa", "America/Managua", "America/El_Salvador", "Etc/GMT+6"],
            ["America/Chicago", "America/Winnipeg", "America/Rainy_River", "America/Rankin_Inlet", "America/Resolute", "America/Matamoros", "America/Indiana/Knox", "America/Indiana/Tell_City", "America/Menominee", "America/North_Dakota/Beulah", "America/North_Dakota/Center", "America/North_Dakota/New_Salem", "CST6CDT"],
            ["Pacific/Easter"],
            ["America/Mexico_City", "America/Bahia_Banderas", "America/Merida", "America/Monterrey"],
            ["America/Regina", "America/Swift_Current"],
            ["America/Bogota", "America/Rio_Branco", "America/Eirunepe", "America/Coral_Harbour", "America/Guayaquil", "America/Jamaica", "America/Cayman", "America/Panama", "America/Lima", "Etc/GMT+5"],
            ["America/Cancun"],
            ["America/New_York", "America/Nassau", "America/Toronto", "America/Iqaluit", "America/Montreal", "America/Nipigon", "America/Pangnirtung", "America/Thunder_Bay", "America/Detroit", "America/Indiana/Petersburg", "America/Indiana/Vincennes", "America/Indiana/Winamac", "America/Kentucky/Monticello", "America/Louisville", "EST5EDT"],
            ["America/Port-au-Prince"],
            ["America/Havana"],
            ["America/Indianapolis", "America/Indiana/Marengo", "America/Indiana/Vevay"],
            ["America/Grand_Turk"],
            ["America/Asuncion"],
            ["America/Halifax", "Atlantic/Bermuda", "America/Glace_Bay", "America/Goose_Bay", "America/Moncton", "America/Thule"],
            ["America/Caracas"],
            ["America/Cuiaba", "America/Campo_Grande"],
            ["America/La_Paz", "America/Antigua", "America/Anguilla", "America/Aruba", "America/Barbados", "America/St_Barthelemy", "America/Kralendijk", "America/Manaus", "America/Boa_Vista", "America/Porto_Velho", "America/Blanc-Sablon", "America/Curacao", "America/Dominica", "America/Santo_Domingo", "America/Grenada", "America/Guadeloupe", "America/Guyana", "America/St_Kitts", "America/St_Lucia", "America/Marigot", "America/Martinique", "America/Montserrat", "America/Puerto_Rico", "America/Lower_Princes", "America/Port_of_Spain", "America/St_Vincent", "America/Tortola", "America/St_Thomas", "Etc/GMT+4"],
            ["America/Santiago"],
            ["America/St_Johns"],
            ["America/Araguaina"],
            ["America/Sao_Paulo"],
            ["America/Cayenne", "Antarctica/Rothera", "America/Fortaleza", "America/Belem", "America/Maceio", "America/Recife", "America/Santarem", "Atlantic/Stanley", "America/Paramaribo", "Etc/GMT+3"],
            ["America/Buenos_Aires", "America/Argentina/La_Rioja", "America/Argentina/Rio_Gallegos", "America/Argentina/Salta", "America/Argentina/San_Juan", "America/Argentina/San_Luis", "America/Argentina/Tucuman", "America/Argentina/Ushuaia", "America/Catamarca", "America/Cordoba", "America/Jujuy", "America/Mendoza"],
            ["America/Godthab"],
            ["America/Montevideo"],
            ["America/Punta_Arenas", "Antarctica/Palmer"],
            ["America/Miquelon"],
            ["America/Bahia"],
            ["Etc/GMT+2", "America/Noronha", "Atlantic/South_Georgia"],
            ["Atlantic/Azores", "America/Scoresbysund"],
            ["Atlantic/Cape_Verde", "Etc/GMT+1"],
            ["Etc/GMT", "America/Danmarkshavn", "Etc/UTC"],
            ["Africa/Casablanca", "Africa/El_Aaiun"],
            ["Europe/London", "Atlantic/Canary", "Atlantic/Faeroe", "Europe/Guernsey", "Europe/Dublin", "Europe/Isle_of_Man", "Europe/Jersey", "Europe/Lisbon", "Atlantic/Madeira"],
            ["Atlantic/Reykjavik", "Africa/Ouagadougou", "Africa/Abidjan", "Africa/Accra", "Africa/Banjul", "Africa/Conakry", "Africa/Bissau", "Africa/Monrovia", "Africa/Bamako", "Africa/Nouakchott", "Atlantic/St_Helena", "Africa/Freetown", "Africa/Dakar", "Africa/Lome"],
            ["Europe/Berlin", "Europe/Andorra", "Europe/Vienna", "Europe/Zurich", "Europe/Busingen", "Europe/Gibraltar", "Europe/Rome", "Europe/Vaduz", "Europe/Luxembourg", "Europe/Monaco", "Europe/Malta", "Europe/Amsterdam", "Europe/Oslo", "Europe/Stockholm", "Arctic/Longyearbyen", "Europe/San_Marino", "Europe/Vatican"],
            ["Europe/Budapest", "Europe/Tirane", "Europe/Prague", "Europe/Podgorica", "Europe/Belgrade", "Europe/Ljubljana", "Europe/Bratislava"],
            ["Europe/Paris", "Europe/Brussels", "Europe/Copenhagen", "Europe/Madrid", "Africa/Ceuta"],
            ["Europe/Warsaw", "Europe/Sarajevo", "Europe/Zagreb", "Europe/Skopje"],
            ["Africa/Lagos", "Africa/Luanda", "Africa/Porto-Novo", "Africa/Kinshasa", "Africa/Bangui", "Africa/Brazzaville", "Africa/Douala", "Africa/Algiers", "Africa/Libreville", "Africa/Malabo", "Africa/Niamey", "Africa/Sao_Tome", "Africa/Ndjamena", "Africa/Tunis", "Etc/GMT-1"],
            ["Asia/Amman"],
            ["Europe/Bucharest", "Asia/Nicosia", "Europe/Athens"],
            ["Asia/Beirut"],
            ["Africa/Cairo"],
            ["Europe/Chisinau"],
            ["Asia/Damascus"],
            ["Asia/Hebron", "Asia/Gaza"],
            ["Africa/Johannesburg", "Africa/Bujumbura", "Africa/Gaborone", "Africa/Lubumbashi", "Africa/Maseru", "Africa/Blantyre", "Africa/Maputo", "Africa/Kigali", "Africa/Mbabane", "Africa/Lusaka", "Africa/Harare", "Etc/GMT-2"],
            ["Europe/Kiev", "Europe/Mariehamn", "Europe/Sofia", "Europe/Tallinn", "Europe/Helsinki", "Europe/Vilnius", "Europe/Riga", "Europe/Uzhgorod", "Europe/Zaporozhye"],
            ["Asia/Jerusalem"],
            ["Europe/Kaliningrad"],
            ["Africa/Khartoum"],
            ["Africa/Tripoli"],
            ["Africa/Windhoek"],
            ["Asia/Baghdad"],
            ["Europe/Istanbul", "Asia/Famagusta"],
            ["Asia/Riyadh", "Asia/Bahrain", "Asia/Kuwait", "Asia/Qatar", "Asia/Aden"],
            ["Europe/Minsk"],
            ["Europe/Moscow", "Europe/Kirov", "Europe/Volgograd", "Europe/Simferopol"],
            ["Africa/Nairobi", "Antarctica/Syowa", "Africa/Djibouti", "Africa/Asmera", "Africa/Addis_Ababa", "Indian/Comoro", "Indian/Antananarivo", "Africa/Mogadishu", "Africa/Juba", "Africa/Dar_es_Salaam", "Africa/Kampala", "Indian/Mayotte", "Etc/GMT-3"],
            ["Asia/Tehran"],
            ["Asia/Dubai", "Asia/Muscat", "Etc/GMT-4"],
            ["Europe/Astrakhan", "Europe/Ulyanovsk"],
            ["Asia/Baku"],
            ["Europe/Samara"],
            ["Indian/Mauritius", "Indian/Reunion", "Indian/Mahe"],
            ["Europe/Saratov"],
            ["Asia/Tbilisi"],
            ["Asia/Yerevan"],
            ["Asia/Kabul"],
            ["Asia/Tashkent", "Antarctica/Mawson", "Asia/Oral", "Asia/Aqtau", "Asia/Aqtobe", "Asia/Atyrau", "Indian/Maldives", "Indian/Kerguelen", "Asia/Dushanbe", "Asia/Ashgabat", "Asia/Samarkand", "Etc/GMT-5"],
            ["Asia/Yekaterinburg"],
            ["Asia/Karachi"],
            ["Asia/Calcutta"],
            ["Asia/Colombo"],
            ["Asia/Katmandu"],
            ["Asia/Almaty", "Antarctica/Vostok", "Asia/Urumqi", "Indian/Chagos", "Asia/Bishkek", "Asia/Qyzylorda", "Etc/GMT-6"],
            ["Asia/Dhaka", "Asia/Thimphu"],
            ["Asia/Omsk"],
            ["Asia/Rangoon", "Indian/Cocos"],
            ["Asia/Bangkok", "Antarctica/Davis", "Indian/Christmas", "Asia/Jakarta", "Asia/Pontianak", "Asia/Phnom_Penh", "Asia/Vientiane", "Asia/Saigon", "Etc/GMT-7"],
            ["Asia/Barnaul"],
            ["Asia/Hovd"],
            ["Asia/Krasnoyarsk", "Asia/Novokuznetsk"],
            ["Asia/Novosibirsk"],
            ["Asia/Tomsk"],
            ["Asia/Shanghai", "Asia/Hong_Kong", "Asia/Macau"],
            ["Asia/Irkutsk"],
            ["Asia/Singapore", "Asia/Brunei", "Asia/Makassar", "Asia/Kuala_Lumpur", "Asia/Kuching", "Asia/Manila", "Etc/GMT-8"],
            ["Australia/Perth"],
            ["Asia/Taipei"],
            ["Asia/Ulaanbaatar", "Asia/Choibalsan"],
            ["Asia/Pyongyang"],
            ["Australia/Eucla"],
            ["Asia/Chita"],
            ["Asia/Tokyo", "Asia/Jayapura", "Pacific/Palau", "Asia/Dili", "Etc/GMT-9"],
            ["Asia/Seoul"],
            ["Asia/Yakutsk", "Asia/Khandyga"],
            ["Australia/Adelaide", "Australia/Broken_Hill"],
            ["Australia/Darwin"],
            ["Australia/Brisbane", "Australia/Lindeman"],
            ["Australia/Sydney", "Australia/Melbourne"],
            ["Pacific/Port_Moresby", "Antarctica/DumontDUrville", "Pacific/Truk", "Pacific/Guam", "Pacific/Saipan", "Etc/GMT-10"],
            ["Australia/Hobart", "Australia/Currie"],
            ["Asia/Vladivostok", "Asia/Ust-Nera"],
            ["Australia/Lord_Howe"],
            ["Pacific/Bougainville"],
            ["Asia/Srednekolymsk"],
            ["Asia/Magadan"],
            ["Pacific/Norfolk"],
            ["Asia/Sakhalin"],
            ["Pacific/Guadalcanal", "Antarctica/Casey", "Antarctica/Macquarie", "Pacific/Ponape", "Pacific/Kosrae", "Pacific/Noumea", "Pacific/Efate", "Etc/GMT-11"],
            ["Asia/Kamchatka", "Asia/Anadyr"],
            ["Pacific/Auckland", "Antarctica/McMurdo"],
            ["Etc/GMT-12", "Pacific/Tarawa", "Pacific/Majuro", "Pacific/Kwajalein", "Pacific/Nauru", "Pacific/Funafuti", "Pacific/Wake", "Pacific/Wallis"],
            ["Pacific/Fiji"],
            ["Pacific/Chatham"],
            ["Etc/GMT-13", "Pacific/Enderbury", "Pacific/Fakaofo"],
            ["Pacific/Tongatapu"],
            ["Pacific/Apia"],
            ["Pacific/Kiritimati", "Etc/GMT-14"]
        ]
    };
    extend(ns('DW.ScheduleComponent'), {
        TimeZoneMapping: TimeZoneMapping
    });
}));
