//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocuWare.Web.Mvc.Resources.SharedResources.Components.AppComponents.AuditReport.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AuditReport {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuditReport() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DocuWare.Web.Mvc.Resources.SharedResources.Components.AppComponents.AuditReport.L" +
                            "ocalization.AuditReport", typeof(AuditReport).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doc Id: {0}.
        /// </summary>
        internal static string AuditEventDetails_DocInfo {
            get {
                return ResourceManager.GetString("AuditEventDetails_DocInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed properties:.
        /// </summary>
        internal static string AuditEventDetails_Label {
            get {
                return ResourceManager.GetString("AuditEventDetails_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit.
        /// </summary>
        internal static string AuditReport_Default_FileName {
            get {
                return ResourceManager.GetString("AuditReport_Default_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed.
        /// </summary>
        internal static string AuditReport_EventType_Changed {
            get {
                return ResourceManager.GetString("AuditReport_EventType_Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout to File System.
        /// </summary>
        internal static string AuditReport_EventType_CheckoutToFileSystem {
            get {
                return ResourceManager.GetString("AuditReport_EventType_CheckoutToFileSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout to Tray.
        /// </summary>
        internal static string AuditReport_EventType_CheckoutToTray {
            get {
                return ResourceManager.GetString("AuditReport_EventType_CheckoutToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clip.
        /// </summary>
        internal static string AuditReport_EventType_Clip {
            get {
                return ResourceManager.GetString("AuditReport_EventType_Clip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to Tray.
        /// </summary>
        internal static string AuditReport_EventType_CopyToTray {
            get {
                return ResourceManager.GetString("AuditReport_EventType_CopyToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string AuditReport_EventType_Created {
            get {
                return ResourceManager.GetString("AuditReport_EventType_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Request.
        /// </summary>
        internal static string AuditReport_EventType_CreateRequest {
            get {
                return ResourceManager.GetString("AuditReport_EventType_CreateRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Settings.
        /// </summary>
        internal static string AuditReport_EventType_CreateSettings {
            get {
                return ResourceManager.GetString("AuditReport_EventType_CreateSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string AuditReport_EventType_Delete {
            get {
                return ResourceManager.GetString("AuditReport_EventType_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string AuditReport_EventType_DeleteAudit {
            get {
                return ResourceManager.GetString("AuditReport_EventType_DeleteAudit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        internal static string AuditReport_EventType_Deleted {
            get {
                return ResourceManager.GetString("AuditReport_EventType_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Settings.
        /// </summary>
        internal static string AuditReport_EventType_DeleteSettings {
            get {
                return ResourceManager.GetString("AuditReport_EventType_DeleteSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Version History.
        /// </summary>
        internal static string AuditReport_EventType_DeleteVersionHistory {
            get {
                return ResourceManager.GetString("AuditReport_EventType_DeleteVersionHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        internal static string AuditReport_EventType_DisableAudit {
            get {
                return ResourceManager.GetString("AuditReport_EventType_DisableAudit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Annotations.
        /// </summary>
        internal static string AuditReport_EventType_EditAnnotations {
            get {
                return ResourceManager.GetString("AuditReport_EventType_EditAnnotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Content.
        /// </summary>
        internal static string AuditReport_EventType_EditContent {
            get {
                return ResourceManager.GetString("AuditReport_EventType_EditContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed.
        /// </summary>
        internal static string AuditReport_EventType_Edited {
            get {
                return ResourceManager.GetString("AuditReport_EventType_Edited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Index Data.
        /// </summary>
        internal static string AuditReport_EventType_EditIndexData {
            get {
                return ResourceManager.GetString("AuditReport_EventType_EditIndexData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Settings.
        /// </summary>
        internal static string AuditReport_EventType_EditSettings {
            get {
                return ResourceManager.GetString("AuditReport_EventType_EditSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string AuditReport_EventType_Email {
            get {
                return ResourceManager.GetString("AuditReport_EventType_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string AuditReport_EventType_EnableAudit {
            get {
                return ResourceManager.GetString("AuditReport_EventType_EnableAudit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string AuditReport_EventType_Export {
            get {
                return ResourceManager.GetString("AuditReport_EventType_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string AuditReport_EventType_LogIn {
            get {
                return ResourceManager.GetString("AuditReport_EventType_LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        internal static string AuditReport_EventType_LogOff {
            get {
                return ResourceManager.GetString("AuditReport_EventType_LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string AuditReport_EventType_Open {
            get {
                return ResourceManager.GetString("AuditReport_EventType_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string AuditReport_EventType_Print {
            get {
                return ResourceManager.GetString("AuditReport_EventType_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        internal static string AuditReport_EventType_Store {
            get {
                return ResourceManager.GetString("AuditReport_EventType_Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo Checkout.
        /// </summary>
        internal static string AuditReport_EventType_UndoCheckout {
            get {
                return ResourceManager.GetString("AuditReport_EventType_UndoCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Decision made.
        /// </summary>
        internal static string AuditReport_EventType_WorkflowDecisionMade {
            get {
                return ResourceManager.GetString("AuditReport_EventType_WorkflowDecisionMade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified.
        /// </summary>
        internal static string AuditReport_LastModified {
            get {
                return ResourceManager.GetString("AuditReport_LastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Data.
        /// </summary>
        internal static string AuditReport_ObjectName_AllData {
            get {
                return ResourceManager.GetString("AuditReport_ObjectName_AllData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration changes.
        /// </summary>
        internal static string AuditReport_ObjectName_ConfigurationChanges {
            get {
                return ResourceManager.GetString("AuditReport_ObjectName_ConfigurationChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Events.
        /// </summary>
        internal static string AuditReport_ObjectName_DocumentEvent {
            get {
                return ResourceManager.GetString("AuditReport_ObjectName_DocumentEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Login/Logout.
        /// </summary>
        internal static string AuditReport_ObjectName_UserLogEvent {
            get {
                return ResourceManager.GetString("AuditReport_ObjectName_UserLogEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditing.
        /// </summary>
        internal static string AuditReport_SettingsType_Auditing {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_Auditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Server.
        /// </summary>
        internal static string AuditReport_SettingsType_AuthenticationServer {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_AuthenticationServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoindex.
        /// </summary>
        internal static string AuditReport_SettingsType_Autoindex {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_Autoindex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Number.
        /// </summary>
        internal static string AuditReport_SettingsType_AutoNumber {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_AutoNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Use Case.
        /// </summary>
        internal static string AuditReport_SettingsType_BusinessUseCase {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_BusinessUseCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to Outlook.
        /// </summary>
        internal static string AuditReport_SettingsType_ConnectToOutlook {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_ConnectToOutlook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to Outlook access.
        /// </summary>
        internal static string AuditReport_SettingsType_ConnectToOutlookAccess {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_ConnectToOutlookAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to Outlook Configuration.
        /// </summary>
        internal static string AuditReport_SettingsType_ConnectToOutlookConfiguration {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_ConnectToOutlookConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string AuditReport_SettingsType_Database {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Connection.
        /// </summary>
        internal static string AuditReport_SettingsType_DatabaseConnection {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_DatabaseConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion.
        /// </summary>
        internal static string AuditReport_SettingsType_Deletion {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_Deletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk.
        /// </summary>
        internal static string AuditReport_SettingsType_Disk {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_Disk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        internal static string AuditReport_SettingsType_Document {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Settings.
        /// </summary>
        internal static string AuditReport_SettingsType_DocumentSettings {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_DocumentSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type.
        /// </summary>
        internal static string AuditReport_SettingsType_DocumentType {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_DocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocuWare Import Request.
        /// </summary>
        internal static string AuditReport_SettingsType_DwImportRequest {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_DwImportRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocuWare Request Lite.
        /// </summary>
        internal static string AuditReport_SettingsType_DwRequestLite {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_DwRequestLite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Configuration.
        /// </summary>
        internal static string AuditReport_SettingsType_EmailConfiguration {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_EmailConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string AuditReport_SettingsType_Export {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Select List.
        /// </summary>
        internal static string AuditReport_SettingsType_ExternalSelectList {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_ExternalSelectList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External User Directory.
        /// </summary>
        internal static string AuditReport_SettingsType_ExternalUserDirectory {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_ExternalUserDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field.
        /// </summary>
        internal static string AuditReport_SettingsType_Field {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Cabinet.
        /// </summary>
        internal static string AuditReport_SettingsType_FileCabinet {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_FileCabinet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Cabinet General.
        /// </summary>
        internal static string AuditReport_SettingsType_FileCabinetGeneral {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_FileCabinetGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Cabinet Settings.
        /// </summary>
        internal static string AuditReport_SettingsType_FileCabinetSettings {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_FileCabinetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Connection.
        /// </summary>
        internal static string AuditReport_SettingsType_FileConnection {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_FileConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Extension.
        /// </summary>
        internal static string AuditReport_SettingsType_FileExtension {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_FileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Select List.
        /// </summary>
        internal static string AuditReport_SettingsType_FixedSelectList {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_FixedSelectList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forms.
        /// </summary>
        internal static string AuditReport_SettingsType_Forms {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_Forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Profile.
        /// </summary>
        internal static string AuditReport_SettingsType_GeneralProfile {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_GeneralProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General System.
        /// </summary>
        internal static string AuditReport_SettingsType_GeneralSystem {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_GeneralSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string AuditReport_SettingsType_Group {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligent Indexing Connection.
        /// </summary>
        internal static string AuditReport_SettingsType_IntellixConnection {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_IntellixConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence.
        /// </summary>
        internal static string AuditReport_SettingsType_Licence {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_Licence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        internal static string AuditReport_SettingsType_Link {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MFP Device.
        /// </summary>
        internal static string AuditReport_SettingsType_MfpDevice {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_MfpDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MFP Workflow.
        /// </summary>
        internal static string AuditReport_SettingsType_MfpWorkflow {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_MfpWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Server.
        /// </summary>
        internal static string AuditReport_SettingsType_NotificationServer {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_NotificationServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Settings.
        /// </summary>
        internal static string AuditReport_SettingsType_NotificationSettings {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_NotificationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obr.
        /// </summary>
        internal static string AuditReport_SettingsType_Obr {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_Obr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocr.
        /// </summary>
        internal static string AuditReport_SettingsType_Ocr {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_Ocr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        internal static string AuditReport_SettingsType_Organization {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Configuration of type Printer.
        /// </summary>
        internal static string AuditReport_SettingsType_PrinterConfiguration {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_PrinterConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Server.
        /// </summary>
        internal static string AuditReport_SettingsType_ProcessServer {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_ProcessServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string AuditReport_SettingsType_Profile {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular Expression.
        /// </summary>
        internal static string AuditReport_SettingsType_RegularExpression {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_RegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replication.
        /// </summary>
        internal static string AuditReport_SettingsType_Replication {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_Replication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result List.
        /// </summary>
        internal static string AuditReport_SettingsType_ResultList {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_ResultList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string AuditReport_SettingsType_Role {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedules.
        /// </summary>
        internal static string AuditReport_SettingsType_Schedules {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_Schedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Dialog.
        /// </summary>
        internal static string AuditReport_SettingsType_SearchDialog {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_SearchDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Connect.
        /// </summary>
        internal static string AuditReport_SettingsType_SmartConnect {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_SmartConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smtp Connection.
        /// </summary>
        internal static string AuditReport_SettingsType_SmtpConnection {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_SmtpConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solr Connection.
        /// </summary>
        internal static string AuditReport_SettingsType_SolrConnection {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_SolrConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stamp.
        /// </summary>
        internal static string AuditReport_SettingsType_Stamp {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_Stamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Location.
        /// </summary>
        internal static string AuditReport_SettingsType_StorageLocation {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_StorageLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Dialog.
        /// </summary>
        internal static string AuditReport_SettingsType_StoreDialog {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_StoreDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substitution List.
        /// </summary>
        internal static string AuditReport_SettingsType_SubstitutionList {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_SubstitutionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substitution Rules.
        /// </summary>
        internal static string AuditReport_SettingsType_SubstitutionRules {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_SubstitutionRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Backup Workflow.
        /// </summary>
        internal static string AuditReport_SettingsType_SystemBackupWorkflow {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_SystemBackupWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trusted User.
        /// </summary>
        internal static string AuditReport_SettingsType_TrustedUser {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_TrustedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string AuditReport_SettingsType_User {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Login Logout.
        /// </summary>
        internal static string AuditReport_SettingsType_UserLoginLogout {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_UserLoginLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Synchronization.
        /// </summary>
        internal static string AuditReport_SettingsType_UserSync {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_UserSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tray.
        /// </summary>
        internal static string AuditReport_SettingsType_WebBasket {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_WebBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Connection.
        /// </summary>
        internal static string AuditReport_SettingsType_WebConnection {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_WebConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Instances.
        /// </summary>
        internal static string AuditReport_SettingsType_WebInstances {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_WebInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Service.
        /// </summary>
        internal static string AuditReport_SettingsType_WebServices {
            get {
                return ResourceManager.GetString("AuditReport_SettingsType_WebServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download as CSV.
        /// </summary>
        internal static string AuditReport_Table_DownloadCSV {
            get {
                return ResourceManager.GetString("AuditReport_Table_DownloadCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string AuditReport_TableColumn_Date {
            get {
                return ResourceManager.GetString("AuditReport_TableColumn_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocId.
        /// </summary>
        internal static string AuditReport_TableColumn_DocId {
            get {
                return ResourceManager.GetString("AuditReport_TableColumn_DocId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        internal static string AuditReport_TableColumn_Event {
            get {
                return ResourceManager.GetString("AuditReport_TableColumn_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Cabinet.
        /// </summary>
        internal static string AuditReport_TableColumn_FileCabinet {
            get {
                return ResourceManager.GetString("AuditReport_TableColumn_FileCabinet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string AuditReport_TableColumn_Name {
            get {
                return ResourceManager.GetString("AuditReport_TableColumn_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        internal static string AuditReport_TableColumn_Organization {
            get {
                return ResourceManager.GetString("AuditReport_TableColumn_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string AuditReport_TableColumn_Type {
            get {
                return ResourceManager.GetString("AuditReport_TableColumn_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string AuditReport_TableColumn_User {
            get {
                return ResourceManager.GetString("AuditReport_TableColumn_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Value.
        /// </summary>
        internal static string AuditReportDetails_TableColumn_PreviousValue {
            get {
                return ResourceManager.GetString("AuditReportDetails_TableColumn_PreviousValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string AuditReportDetails_TableColumn_Property {
            get {
                return ResourceManager.GetString("AuditReportDetails_TableColumn_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string AuditReportDetails_TableColumn_Value {
            get {
                return ResourceManager.GetString("AuditReportDetails_TableColumn_Value", resourceCulture);
            }
        }
    }
}
