//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocuWare.Silverlight.WAF.Host.Localization.QueryBuilder {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class QueryBuilder {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QueryBuilder() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DocuWare.Silverlight.WAF.Host.Localization.QueryBuilder.QueryBuilder", typeof(QueryBuilder).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After the next.
        /// </summary>
        internal static string QueryBuilder_AfterTheNext {
            get {
                return ResourceManager.GetString("QueryBuilder_AfterTheNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After the past.
        /// </summary>
        internal static string QueryBuilder_AfterThePast {
            get {
                return ResourceManager.GetString("QueryBuilder_AfterThePast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AND.
        /// </summary>
        internal static string QueryBuilder_And {
            get {
                return ResourceManager.GetString("QueryBuilder_And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before the next.
        /// </summary>
        internal static string QueryBuilder_BeforeTheNext {
            get {
                return ResourceManager.GetString("QueryBuilder_BeforeTheNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before the past.
        /// </summary>
        internal static string QueryBuilder_BeforeThePast {
            get {
                return ResourceManager.GetString("QueryBuilder_BeforeThePast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        internal static string QueryBuilder_Contains {
            get {
                return ResourceManager.GetString("QueryBuilder_Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid value in the date field..
        /// </summary>
        internal static string QueryBuilder_Err_DateField {
            get {
                return ResourceManager.GetString("QueryBuilder_Err_DateField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid value in the date/time field..
        /// </summary>
        internal static string QueryBuilder_Err_DateTimeField {
            get {
                return ResourceManager.GetString("QueryBuilder_Err_DateTimeField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid value in the decimal field..
        /// </summary>
        internal static string QueryBuilder_Err_DecimalField {
            get {
                return ResourceManager.GetString("QueryBuilder_Err_DecimalField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid range value(s) in the decimal fields..
        /// </summary>
        internal static string QueryBuilder_Err_DecimalRangeField {
            get {
                return ResourceManager.GetString("QueryBuilder_Err_DecimalRangeField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid value in the keyword field..
        /// </summary>
        internal static string QueryBuilder_Err_KeywordField {
            get {
                return ResourceManager.GetString("QueryBuilder_Err_KeywordField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid value in the memo field..
        /// </summary>
        internal static string QueryBuilder_Err_MemoField {
            get {
                return ResourceManager.GetString("QueryBuilder_Err_MemoField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid value in the numeric field..
        /// </summary>
        internal static string QueryBuilder_Err_NumericField {
            get {
                return ResourceManager.GetString("QueryBuilder_Err_NumericField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid range value(s) in the numeric fields..
        /// </summary>
        internal static string QueryBuilder_Err_NumericRangeField {
            get {
                return ResourceManager.GetString("QueryBuilder_Err_NumericRangeField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid range value(s) in the date fields..
        /// </summary>
        internal static string QueryBuilder_Err_RangeDateField {
            get {
                return ResourceManager.GetString("QueryBuilder_Err_RangeDateField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid value in the sql field..
        /// </summary>
        internal static string QueryBuilder_Err_SqlField {
            get {
                return ResourceManager.GetString("QueryBuilder_Err_SqlField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid value in the text field.
        /// </summary>
        internal static string QueryBuilder_Err_TextField {
            get {
                return ResourceManager.GetString("QueryBuilder_Err_TextField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users having this profile will only see documents which match the following rules: .
        /// </summary>
        internal static string QueryBuilder_Introduction {
            get {
                return ResourceManager.GetString("QueryBuilder_Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file cabinet field does not exist..
        /// </summary>
        internal static string QueryBuilder_invalidField {
            get {
                return ResourceManager.GetString("QueryBuilder_invalidField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is between.
        /// </summary>
        internal static string QueryBuilder_IsBetween {
            get {
                return ResourceManager.GetString("QueryBuilder_IsBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is empty.
        /// </summary>
        internal static string QueryBuilder_IsEmpty {
            get {
                return ResourceManager.GetString("QueryBuilder_IsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is equal.
        /// </summary>
        internal static string QueryBuilder_IsEqual {
            get {
                return ResourceManager.GetString("QueryBuilder_IsEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not empty.
        /// </summary>
        internal static string QueryBuilder_IsNotEmpty {
            get {
                return ResourceManager.GetString("QueryBuilder_IsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not equal.
        /// </summary>
        internal static string QueryBuilder_IsNotEqual {
            get {
                return ResourceManager.GetString("QueryBuilder_IsNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is (where clause).
        /// </summary>
        internal static string QueryBuilder_IsWhereClause {
            get {
                return ResourceManager.GetString("QueryBuilder_IsWhereClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR.
        /// </summary>
        internal static string QueryBuilder_Or {
            get {
                return ResourceManager.GetString("QueryBuilder_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to look for QueryBuilder_ProfileIntroduction key.
        /// </summary>
        internal static string QueryBuilder_ProfileIntroduction {
            get {
                return ResourceManager.GetString("QueryBuilder_ProfileIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk Number.
        /// </summary>
        internal static string QueryBuilder_SystemField_DWDISK {
            get {
                return ResourceManager.GetString("QueryBuilder_SystemField_DWDISK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doc ID.
        /// </summary>
        internal static string QueryBuilder_SystemField_DWDOCID {
            get {
                return ResourceManager.GetString("QueryBuilder_SystemField_DWDOCID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Access Date.
        /// </summary>
        internal static string QueryBuilder_SystemField_DWLASTACCESSDATETIME {
            get {
                return ResourceManager.GetString("QueryBuilder_SystemField_DWLASTACCESSDATETIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Access User.
        /// </summary>
        internal static string QueryBuilder_SystemField_DWLASTACCESSUSER {
            get {
                return ResourceManager.GetString("QueryBuilder_SystemField_DWLASTACCESSUSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification Date.
        /// </summary>
        internal static string QueryBuilder_SystemField_DWMODDATETIME {
            get {
                return ResourceManager.GetString("QueryBuilder_SystemField_DWMODDATETIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification User.
        /// </summary>
        internal static string QueryBuilder_SystemField_DWMODUSER {
            get {
                return ResourceManager.GetString("QueryBuilder_SystemField_DWMODUSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Count.
        /// </summary>
        internal static string QueryBuilder_SystemField_DWSECTIONCOUNT {
            get {
                return ResourceManager.GetString("QueryBuilder_SystemField_DWSECTIONCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP Date Time.
        /// </summary>
        internal static string QueryBuilder_SystemField_DWSAPDATETIME {
            get {
                return ResourceManager.GetString("QueryBuilder_SystemField_DWSAPDATETIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP Status.
        /// </summary>
        internal static string QueryBuilder_SystemField_DWSAPSTATUS {
            get {
                return ResourceManager.GetString("QueryBuilder_SystemField_DWSAPSTATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Date.
        /// </summary>
        internal static string QueryBuilder_SystemField_DWSTOREDATETIME {
            get {
                return ResourceManager.GetString("QueryBuilder_SystemField_DWSTOREDATETIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store User.
        /// </summary>
        internal static string QueryBuilder_SystemField_DWSTOREUSER {
            get {
                return ResourceManager.GetString("QueryBuilder_SystemField_DWSTOREUSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Version.
        /// </summary>
        internal static string QueryBuilder_SystemField_DWUSRVERSION {
            get {
                return ResourceManager.GetString("QueryBuilder_SystemField_DWUSRVERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Comment.
        /// </summary>
        internal static string QueryBuilder_SystemField_DWVERSIONCOMMENT {
            get {
                return ResourceManager.GetString("QueryBuilder_SystemField_DWVERSIONCOMMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Status.
        /// </summary>
        internal static string QueryBuilder_SystemField_DWVERSTATUS {
            get {
                return ResourceManager.GetString("QueryBuilder_SystemField_DWVERSTATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP Doc Id.
        /// </summary>
        internal static string QueryBuilder_SystemField_SAPDOCID {
            get {
                return ResourceManager.GetString("QueryBuilder_SystemField_SAPDOCID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP Doc Type.
        /// </summary>
        internal static string QueryBuilder_SystemField_SAPDOCTYPE {
            get {
                return ResourceManager.GetString("QueryBuilder_SystemField_SAPDOCTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP Protection Type.
        /// </summary>
        internal static string QueryBuilder_SystemField_SAPPROTECTIONTYPE {
            get {
                return ResourceManager.GetString("QueryBuilder_SystemField_SAPPROTECTIONTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Fields.
        /// </summary>
        internal static string QueryBuilder_SystemFields {
            get {
                return ResourceManager.GetString("QueryBuilder_SystemFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Within the next.
        /// </summary>
        internal static string QueryBuilder_WithinTheNext {
            get {
                return ResourceManager.GetString("QueryBuilder_WithinTheNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Within the past.
        /// </summary>
        internal static string QueryBuilder_WithinThePast {
            get {
                return ResourceManager.GetString("QueryBuilder_WithinThePast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No rules are defined yet..
        /// </summary>
        internal static string QueryClick_LabelFirstPart {
            get {
                return ResourceManager.GetString("QueryClick_LabelFirstPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new rule .
        /// </summary>
        internal static string QueryClick_LabelSecondPart {
            get {
                return ResourceManager.GetString("QueryClick_LabelSecondPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a group of rules.
        /// </summary>
        internal static string QueryClick_LabelThirdPart {
            get {
                return ResourceManager.GetString("QueryClick_LabelThirdPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        internal static string QueryDate_Days {
            get {
                return ResourceManager.GetString("QueryDate_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        internal static string QueryDate_Hours {
            get {
                return ResourceManager.GetString("QueryDate_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months.
        /// </summary>
        internal static string QueryDate_Months {
            get {
                return ResourceManager.GetString("QueryDate_Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        internal static string QueryDate_Years {
            get {
                return ResourceManager.GetString("QueryDate_Years", resourceCulture);
            }
        }
    }
}
