// at this time this file has to be maintained manually

declare module dev.docuware.com.services {
    interface ISettingsService {
        login(request: dev.docuware.com.services.settings.Login): dev.docuware.com.services.settings.LoginResponse;
        loginWithToken(request: dev.docuware.com.services.settings.LoginWithToken): dev.docuware.com.services.settings.LoginWithTokenResponse;
        loginWithWindowsAuthentication(request: dev.docuware.com.services.settings.LoginWithWindowsAuthentication): dev.docuware.com.services.settings.LoginWithWindowsAuthenticationResponse;
        createLoginToken(request: dev.docuware.com.services.settings.CreateLoginToken): dev.docuware.com.services.settings.CreateLoginTokenResponse;
        logoff(request: dev.docuware.com.services.settings.Logoff): dev.docuware.com.services.settings.LogoffResponse;
        ping(request: dev.docuware.com.services.settings.Ping): dev.docuware.com.services.settings.PingResponse;
        systemUserLogin(request: dev.docuware.com.services.settings.SystemUserLogin): dev.docuware.com.services.settings.SystemUserLoginResponse;
        getVersionInfo(request: dev.docuware.com.services.settings.GetVersionInfo): dev.docuware.com.services.settings.GetVersionInfoResponse;
        getOrganizationIdentities(request: dev.docuware.com.services.settings.GetOrganizationIdentities): dev.docuware.com.services.settings.GetOrganizationIdentitiesResponse;
        getOrganizationHeaders(request: dev.docuware.com.services.settings.GetOrganizationHeaders): dev.docuware.com.services.settings.GetOrganizationHeadersResponse;
        getOrganizations(request: dev.docuware.com.services.settings.GetOrganizations): dev.docuware.com.services.settings.GetOrganizationsResponse;
        createOrganization(request: dev.docuware.com.services.settings.CreateOrganization): dev.docuware.com.services.settings.CreateOrganizationResponse;
        updateOrganization(request: dev.docuware.com.services.settings.UpdateOrganization): dev.docuware.com.services.settings.UpdateOrganizationResponse;
        getServerHeaders(request: dev.docuware.com.services.settings.GetServerHeaders): dev.docuware.com.services.settings.GetServerHeadersResponse;
        getServers(request: dev.docuware.com.services.settings.GetServers): dev.docuware.com.services.settings.GetServersResponse;
        getDatabaseConnectionHeaders(request: dev.docuware.com.services.settings.GetDatabaseConnectionHeaders): dev.docuware.com.services.settings.GetDatabaseConnectionHeadersResponse;
        getDatabaseConnections(request: dev.docuware.com.services.settings.GetDatabaseConnections): dev.docuware.com.services.settings.GetDatabaseConnectionsResponse;
        saveDatabaseConnection(request: dev.docuware.com.services.settings.SaveDatabaseConnection): dev.docuware.com.services.settings.SaveDatabaseConnectionResponse;
        getStorageLocationHeaders(request: dev.docuware.com.services.settings.GetStorageLocationHeaders): dev.docuware.com.services.settings.GetStorageLocationHeadersResponse;
        getStorageLocations(request: dev.docuware.com.services.settings.GetStorageLocations): dev.docuware.com.services.settings.GetStorageLocationsResponse;
        saveStorageLocation(request: dev.docuware.com.services.settings.SaveStorageLocation): dev.docuware.com.services.settings.SaveStorageLocationResponse;
        getFileConnectionHeaders(request: dev.docuware.com.services.settings.GetFileConnectionHeaders): dev.docuware.com.services.settings.GetFileConnectionHeadersResponse;
        getFileConnections(request: dev.docuware.com.services.settings.GetFileConnections): dev.docuware.com.services.settings.GetFileConnectionsResponse;
        saveFileConnection(request: dev.docuware.com.services.settings.SaveFileConnection): dev.docuware.com.services.settings.SaveFileConnectionResponse;
        getSMTPConnectionHeaders(request: dev.docuware.com.services.settings.GetSMTPConnectionHeadersRequest): dev.docuware.com.services.settings.GetSMTPConnectionHeadersResponse;
        getSMTPConnections(request: dev.docuware.com.services.settings.GetSMTPConnectionsRequest): dev.docuware.com.services.settings.GetSMTPConnectionsResponse;
        saveSMTPConnection(request: dev.docuware.com.services.settings.SaveSMTPConnectionRequest): dev.docuware.com.services.settings.SaveSMTPConnectionResponse;
        deleteSMTPConnections(request: dev.docuware.com.services.settings.DeleteSMTPConnectionsRequest): dev.docuware.com.services.settings.DeleteSMTPConnectionsResponse;
        getSolrConnectionHeaders(request: dev.docuware.com.services.settings.GetSolrConnectionHeaders): dev.docuware.com.services.settings.GetSolrConnectionHeadersResponse;
        getSolrConnections(request: dev.docuware.com.services.settings.GetSolrConnections): dev.docuware.com.services.settings.GetSolrConnectionsResponse;
        saveSolrConnection(request: dev.docuware.com.services.settings.SaveSolrConnection): dev.docuware.com.services.settings.SaveSolrConnectionResponse;
        getWebConnectionHeaders(request: dev.docuware.com.services.settings.GetWebConnectionHeaders): dev.docuware.com.services.settings.GetWebConnectionHeadersResponse;
        getWebConnections(request: dev.docuware.com.services.settings.GetWebConnections): dev.docuware.com.services.settings.GetWebConnectionsResponse;
        getIntellixConnectionHeaders(request: dev.docuware.com.services.settings.GetIntellixConnectionHeaders): dev.docuware.com.services.settings.GetIntellixConnectionHeadersResponse;
        getIntellixConnections(request: dev.docuware.com.services.settings.GetIntellixConnections): dev.docuware.com.services.settings.GetIntellixConnectionsResponse;
        installIntellixConnection(request: dev.docuware.com.services.settings.InstallIntellixConnection): dev.docuware.com.services.settings.InstallIntellixConnectionResponse;
        deleteIntellixConnections(request: dev.docuware.com.services.settings.DeleteIntellixConnections): dev.docuware.com.services.settings.DeleteIntellixConnectionsResponse;
        updateIntellixConnection(request: dev.docuware.com.services.settings.UpdateIntellixConnection): dev.docuware.com.services.settings.UpdateIntellixConnectionResponse;
        getExternalAppHeaders(request: dev.docuware.com.services.settings.GetExternalAppHeaders): dev.docuware.com.services.settings.GetExternalAppHeadersResponse;
        getExternalApplicationSettings(request: dev.docuware.com.services.settings.GetExternalApplicationSettings): dev.docuware.com.services.settings.GetExternalApplicationSettingsResponse;
        saveExternalApplicationSetting(request: dev.docuware.com.services.settings.SaveExternalApplicationSetting): dev.docuware.com.services.settings.SaveExternalApplicationSettingResponse;
        deleteExternalApplicationSettings(request: dev.docuware.com.services.settings.DeleteExternalApplicationSettings): dev.docuware.com.services.settings.DeleteExternalApplicationSettingsResponse;
        checkDatabaseConnectionAccess(request: dev.docuware.com.services.settings.CheckDatabaseConnectionAccess): dev.docuware.com.services.settings.CheckDatabaseConnectionAccessResponse;
        getSampleData(request: dev.docuware.com.services.settings.GetSampleData): dev.docuware.com.services.settings.GetSampleDataResponse;
        getRegularExpressions(request: dev.docuware.com.services.settings.GetRegularExpressions): dev.docuware.com.services.settings.GetRegularExpressionsResponse;
        getLastChangedItems(request: dev.docuware.com.services.settings.GetLastChangedItems): dev.docuware.com.services.settings.GetLastChangedItemsResponse;
        getWAFSettings(request: dev.docuware.com.services.settings.GetWAFSettings): dev.docuware.com.services.settings.GetWAFSettingsResponse;
        getWebInstanceHeaders(request: dev.docuware.com.services.settings.GetWebInstanceHeaders): dev.docuware.com.services.settings.GetWebInstanceHeadersResponse;
        getWebInstances(request: dev.docuware.com.services.settings.GetWebInstances): dev.docuware.com.services.settings.GetWebInstancesResponse;
        saveWebInstance(request: dev.docuware.com.services.settings.SaveWebInstance): dev.docuware.com.services.settings.SaveWebInstanceResponse;
        deleteWebInstances(request: dev.docuware.com.services.settings.DeleteWebInstances): dev.docuware.com.services.settings.DeleteWebInstancesResponse;
        getWebInstancesAsXML(request: dev.docuware.com.services.settings.GetWebInstancesAsXML): dev.docuware.com.services.settings.GetWebInstancesAsXMLResponse;
        getDocumentTypes(request: dev.docuware.com.services.settings.GetDocumentTypes): dev.docuware.com.services.settings.GetDocumentTypesResponse;
        getGlobalDocumentTypes(request: dev.docuware.com.services.settings.GetGlobalDocumentTypes): dev.docuware.com.services.settings.GetGlobalDocumentTypesResponse;
        saveDocumentType(request: dev.docuware.com.services.settings.SaveDocumentType): dev.docuware.com.services.settings.SaveDocumentTypeResponse;
        deleteDocumentTypes(request: dev.docuware.com.services.settings.DeleteDocumentTypes): dev.docuware.com.services.settings.DeleteDocumentTypesResponse;
        getSelectListHeaders(request: dev.docuware.com.services.settings.GetSelectListHeaders): dev.docuware.com.services.settings.GetSelectListHeadersResponse;
        getSelectLists(request: dev.docuware.com.services.settings.GetSelectLists): dev.docuware.com.services.settings.GetSelectListsResponse;
        saveSelectList(request: dev.docuware.com.services.settings.SaveSelectList): dev.docuware.com.services.settings.SaveSelectListResponse;
        deleteSelectLists(request: dev.docuware.com.services.settings.DeleteSelectLists): dev.docuware.com.services.settings.DeleteSelectListsResponse;
        getStamps(request: dev.docuware.com.services.settings.GetStamps): dev.docuware.com.services.settings.GetStampsResponse;
        getStampHeaders(request: dev.docuware.com.services.settings.GetStampHeaders): dev.docuware.com.services.settings.GetStampHeadersResponse;
        saveStamp(request: dev.docuware.com.services.settings.SaveStamp): dev.docuware.com.services.settings.SaveStampResponse;
        getSubstitutionRuleHeaders(request: dev.docuware.com.services.settings.GetSubstitutionRuleHeaders): dev.docuware.com.services.settings.GetSubstitutionRuleHeadersResponse;
        getSubstitutionRules(request: dev.docuware.com.services.settings.GetSubstitutionRules): dev.docuware.com.services.settings.GetSubstitutionRulesResponse;
        getSubstitutionListHeaders(request: dev.docuware.com.services.settings.GetSubstitutionListHeaders): dev.docuware.com.services.settings.GetSubstitutionListHeadersResponse;
        getSubstitutionLists(request: dev.docuware.com.services.settings.GetSubstitutionLists ): dev.docuware.com.services.settings.GetSubstitutionListsResponse;
        getDependencies(request: dev.docuware.com.services.settings.GetDependencies ): dev.docuware.com.services.settings.GetDependenciesResponse;
        getFieldDependencies(request: dev.docuware.com.services.settings.GetFieldDependencies ): dev.docuware.com.services.settings.GetFieldDependenciesResponse;
        getFileExtensions(request: dev.docuware.com.services.settings.GetFileExtensions ): dev.docuware.com.services.settings.GetFileExtensionsResponse;
        getFileExtensionHeaders(request: dev.docuware.com.services.settings.GetFileExtensionHeaders): dev.docuware.com.services.settings.GetFileExtensionHeadersResponse;
        getOrgSMTPConnections(request: dev.docuware.com.services.settings.GetOrgSMTPConnectionsRequest): dev.docuware.com.services.settings.GetOrgSMTPConnectionsResponse;
        getOrgSMTPConnectionHeaders(request: dev.docuware.com.services.settings.GetOrgSMTPConnectionHeadersRequest): dev.docuware.com.services.settings.GetOrgSMTPConnectionHeadersResponse;
        saveOrgSMTPConnection(request: dev.docuware.com.services.settings.SaveOrgSMTPConnectionRequest): dev.docuware.com.services.settings.SaveOrgSMTPConnectionResponse;
        deleteOrgSMTPConnections(request: dev.docuware.com.services.settings.DeleteOrgSMTPConnectionsRequest): dev.docuware.com.services.settings.DeleteOrgSMTPConnectionsResponse;
        getSMTPOrgAssignments(request: dev.docuware.com.services.settings.GetSMTPOrgAssignmentsRequest): dev.docuware.com.services.settings.GetSMTPOrgAssignmentsResponse;
        saveSMTPOrgAssignment(request: dev.docuware.com.services.settings.SaveSMTPOrgAssignmentRequest): dev.docuware.com.services.settings.SaveSMTPOrgAssignmentResponse;
        deleteSMTPOrgAssignments(request: dev.docuware.com.services.settings.DeleteSMTPOrgAssignmentsRequest): dev.docuware.com.services.settings.DeleteSMTPOrgAssignmentsResponse;
        countSmartConnects(request: dev.docuware.com.services.settings.CountSmartConnects ): dev.docuware.com.services.settings.CountSmartConnectsResponse;
        getSmartConnectHeaders(request: dev.docuware.com.services.settings.GetSmartConnectHeaders ): dev.docuware.com.services.settings.GetSmartConnectHeadersResponse;
        getSmartConnect(request: dev.docuware.com.services.settings.GetSmartConnect ): dev.docuware.com.services.settings.GetSmartConnectResponse;
        getSmartConnects(request: dev.docuware.com.services.settings.GetSmartConnects ): dev.docuware.com.services.settings.GetSmartConnectsResponse;
        saveSmartConnect(request: dev.docuware.com.services.settings.SaveSmartConnect ): dev.docuware.com.services.settings.SaveSmartConnectResponse;
        deleteSmartConnects(request: dev.docuware.com.services.settings.DeleteSmartConnects ): dev.docuware.com.services.settings.DeleteSmartConnectsResponse;
        getFileCabinetHeaders(request: dev.docuware.com.services.settings.GetFileCabinetHeaders ): dev.docuware.com.services.settings.GetFileCabinetHeadersResponse;
        getFileCabinets(request: dev.docuware.com.services.settings.GetFileCabinets ): dev.docuware.com.services.settings.GetFileCabinetsResponse;
        saveFileCabinet(request: dev.docuware.com.services.settings.SaveFileCabinet ): dev.docuware.com.services.settings.SaveFileCabinetResponse;
        deleteFileCabinets(request: dev.docuware.com.services.settings.DeleteFileCabinets ): dev.docuware.com.services.settings.DeleteFileCabinetsResponse;
        getSearchDialogHeaders(request: dev.docuware.com.services.settings.GetSearchDialogHeaders ): dev.docuware.com.services.settings.GetSearchDialogHeadersResponse;
        getSearchDialog(request: dev.docuware.com.services.settings.GetSearchDialog ): dev.docuware.com.services.settings.GetSearchDialogResponse;
        getSearchDialogs(request: dev.docuware.com.services.settings.GetSearchDialogs ): dev.docuware.com.services.settings.GetSearchDialogsResponse;
        saveSearchDialog(request: dev.docuware.com.services.settings.SaveSearchDialog ): dev.docuware.com.services.settings.SaveSearchDialogResponse;
        deleteSearchDialogs(request: dev.docuware.com.services.settings.DeleteSearchDialogs ): dev.docuware.com.services.settings.DeleteSearchDialogsResponse;
        getStoreDialogHeaders(request: dev.docuware.com.services.settings.GetStoreDialogHeaders ): dev.docuware.com.services.settings.GetStoreDialogHeadersResponse;
        getStoreDialog(request: dev.docuware.com.services.settings.GetStoreDialog ): dev.docuware.com.services.settings.GetStoreDialogResponse;
        getStoreDialogs(request: dev.docuware.com.services.settings.GetStoreDialogs ): dev.docuware.com.services.settings.GetStoreDialogsResponse;
        saveStoreDialog(request: dev.docuware.com.services.settings.SaveStoreDialog ): dev.docuware.com.services.settings.SaveStoreDialogResponse;
        deleteStoreDialogs(request: dev.docuware.com.services.settings.DeleteStoreDialogs ): dev.docuware.com.services.settings.DeleteStoreDialogsResponse;
        getResultListHeaders(request: dev.docuware.com.services.settings.GetResultListHeaders ): dev.docuware.com.services.settings.GetResultListHeadersResponse;
        getResultList(request: dev.docuware.com.services.settings.GetResultList ): dev.docuware.com.services.settings.GetResultListResponse;
        getResultLists(request: dev.docuware.com.services.settings.GetResultLists ): dev.docuware.com.services.settings.GetResultListsResponse;
        saveResultList(request: dev.docuware.com.services.settings.SaveResultList ): dev.docuware.com.services.settings.SaveResultListResponse;
        deleteResultLists(request: dev.docuware.com.services.settings.DeleteResultLists ): dev.docuware.com.services.settings.DeleteResultListsResponse;
        getTreeViewHeaders(request: dev.docuware.com.services.settings.GetTreeViewHeaders ): dev.docuware.com.services.settings.GetTreeViewHeadersResponse;
        getTreeView(request: dev.docuware.com.services.settings.GetTreeView ): dev.docuware.com.services.settings.GetTreeViewResponse;
        getTreeViews(request: dev.docuware.com.services.settings.GetTreeViews ): dev.docuware.com.services.settings.GetTreeViewsResponse;
        saveTreeView(request: dev.docuware.com.services.settings.SaveTreeView ): dev.docuware.com.services.settings.SaveTreeViewResponse;
        deleteTreeViews(request: dev.docuware.com.services.settings.DeleteTreeViews ): dev.docuware.com.services.settings.DeleteTreeViewsResponse;
        getInfoDialogHeaders(request: dev.docuware.com.services.settings.GetInfoDialogHeaders ): dev.docuware.com.services.settings.GetInfoDialogHeadersResponse;
        getInfoDialog(request: dev.docuware.com.services.settings.GetInfoDialog ): dev.docuware.com.services.settings.GetInfoDialogResponse;
        getInfoDialogs(request: dev.docuware.com.services.settings.GetInfoDialogs ): dev.docuware.com.services.settings.GetInfoDialogsResponse;
        saveInfoDialog(request: dev.docuware.com.services.settings.SaveInfoDialog ): dev.docuware.com.services.settings.SaveInfoDialogResponse;
        getTaskListHeaders(request: dev.docuware.com.services.settings.GetTaskListHeaders ): dev.docuware.com.services.settings.GetTaskListHeadersResponse;
        getTaskList(request: dev.docuware.com.services.settings.GetTaskList ): dev.docuware.com.services.settings.GetTaskListResponse;
        getTaskLists(request: dev.docuware.com.services.settings.GetTaskLists ): dev.docuware.com.services.settings.GetTaskListsResponse;
        saveTaskList(request: dev.docuware.com.services.settings.SaveTaskList ): dev.docuware.com.services.settings.SaveTaskListResponse;
        deleteTaskLists(request: dev.docuware.com.services.settings.DeleteTaskLists ): dev.docuware.com.services.settings.DeleteTaskListsResponse;
        getFileCabinetProfileHeaders(request: dev.docuware.com.services.settings.GetFileCabinetProfileHeaders ): dev.docuware.com.services.settings.GetFileCabinetProfileHeadersResponse;
        getFileCabinetProfiles(request: dev.docuware.com.services.settings.GetFileCabinetProfiles ): dev.docuware.com.services.settings.GetFileCabinetProfilesResponse;
        saveFileCabinetProfile(request: dev.docuware.com.services.settings.SaveFileCabinetProfile ): dev.docuware.com.services.settings.SaveFileCabinetProfileResponse;
        deleteFileCabinetProfiles(request: dev.docuware.com.services.settings.DeleteFileCabinetProfiles ): dev.docuware.com.services.settings.DeleteFileCabinetProfilesResponse;
        getDocumentLinkHeaders(request: dev.docuware.com.services.settings.GetDocumentLinkHeaders ): dev.docuware.com.services.settings.GetDocumentLinkHeadersResponse;
        getDocumentLinks(request: dev.docuware.com.services.settings.GetDocumentLinks ): dev.docuware.com.services.settings.GetDocumentLinksResponse;
        saveField(request: dev.docuware.com.services.settings.SaveField ): dev.docuware.com.services.settings.SaveFieldResponse;
        deleteField(request: dev.docuware.com.services.settings.DeleteField ): dev.docuware.com.services.settings.DeleteFieldResponse;
        getAutoNumberHeaders(request: dev.docuware.com.services.settings.GetAutoNumberHeaders ): dev.docuware.com.services.settings.GetAutoNumberHeadersResponse;
        getAutoNumbers(request: dev.docuware.com.services.settings.GetAutoNumbers ): dev.docuware.com.services.settings.GetAutoNumbersResponse;
        saveAutoNumber(request: dev.docuware.com.services.settings.SaveAutoNumber ): dev.docuware.com.services.settings.SaveAutoNumberResponse;
        deleteAutoNumbers(request: dev.docuware.com.services.settings.DeleteAutoNumbers ): dev.docuware.com.services.settings.DeleteAutoNumbersResponse;
        changeUserPassword(request: dev.docuware.com.services.settings.ChangeUserPassword ): dev.docuware.com.services.settings.ChangeUserPasswordResponse;
        getPictures(request: dev.docuware.com.services.settings.GetPictures ): dev.docuware.com.services.settings.GetPicturesResponse;
        setPicture(request: dev.docuware.com.services.settings.SetPicture ): dev.docuware.com.services.settings.SetPictureResponse;
        getUserHeaders(request: dev.docuware.com.services.settings.GetUserHeaders ): dev.docuware.com.services.settings.GetUserHeadersResponse;
        getUsers(request: dev.docuware.com.services.settings.GetUsers ): dev.docuware.com.services.settings.GetUsersResponse;
        saveUser(request: dev.docuware.com.services.settings.SaveUser ): dev.docuware.com.services.settings.SaveUserResponse;
        deleteUsers(request: dev.docuware.com.services.settings.DeleteUsers ): dev.docuware.com.services.settings.DeleteUsersResponse;
        getTrustedUserHeaders(request: dev.docuware.com.services.settings.GetTrustedUserHeaders ): dev.docuware.com.services.settings.GetTrustedUserHeadersResponse;
        getTrustedUsers(request: dev.docuware.com.services.settings.GetTrustedUsers ): dev.docuware.com.services.settings.GetTrustedUsersResponse;
        getRoleHeaders(request: dev.docuware.com.services.settings.GetRoleHeaders ): dev.docuware.com.services.settings.GetRoleHeadersResponse;
        getRoles(request: dev.docuware.com.services.settings.GetRoles ): dev.docuware.com.services.settings.GetRolesResponse;
        saveRole(request: dev.docuware.com.services.settings.SaveRole ): dev.docuware.com.services.settings.SaveRoleResponse;
        deleteRoles(request: dev.docuware.com.services.settings.DeleteRoles ): dev.docuware.com.services.settings.DeleteRolesResponse;
        getGeneralProfileHeaders(request: dev.docuware.com.services.settings.GetGeneralProfileHeaders ): dev.docuware.com.services.settings.GetGeneralProfileHeadersResponse;
        getGeneralProfiles(request: dev.docuware.com.services.settings.GetGeneralProfiles ): dev.docuware.com.services.settings.GetGeneralProfilesResponse;
        saveGeneralProfile(request: dev.docuware.com.services.settings.SaveGeneralProfile ): dev.docuware.com.services.settings.SaveGeneralProfileResponse;
        deleteGeneralProfiles(request: dev.docuware.com.services.settings.DeleteGeneralProfiles ): dev.docuware.com.services.settings.DeleteGeneralProfilesResponse;
        getGroupHeaders(request: dev.docuware.com.services.settings.GetGroupHeaders ): dev.docuware.com.services.settings.GetGroupHeadersResponse;
        getGroups(request: dev.docuware.com.services.settings.GetGroups ): dev.docuware.com.services.settings.GetGroupsResponse;
        saveGroup(request: dev.docuware.com.services.settings.SaveGroup ): dev.docuware.com.services.settings.SaveGroupResponse;
        deleteGroups(request: dev.docuware.com.services.settings.DeleteGroups ): dev.docuware.com.services.settings.DeleteGroupsResponse;
        existRelationship(request: dev.docuware.com.services.settings.ExistRelationship ): dev.docuware.com.services.settings.ExistRelationshipResponse;
        addRelationships(request: dev.docuware.com.services.settings.AddRelationships ): dev.docuware.com.services.settings.AddRelationshipsResponse;
        removeRelationships(request: dev.docuware.com.services.settings.RemoveRelationships ): dev.docuware.com.services.settings.RemoveRelationshipsResponse;
        getRelationships(request: dev.docuware.com.services.settings.GetRelationships ): dev.docuware.com.services.settings.GetRelationshipsResponse;
        replaceRelationships(request: dev.docuware.com.services.settings.ReplaceRelationships ): dev.docuware.com.services.settings.ReplaceRelationshipsResponse;
        takeOwnershipOfUserDependencies(request: dev.docuware.com.services.settings.TakeOwnershipOfUserDependencies ): dev.docuware.com.services.settings.TakeOwnershipOfUserDependenciesResponse;
        getWebBasketLocations(request: dev.docuware.com.services.settings.GetWebBasketLocations ): dev.docuware.com.services.settings.GetWebBasketLocationsResponse;
        saveBasketLocation(request: dev.docuware.com.services.settings.SaveBasketLocation ): dev.docuware.com.services.settings.SaveBasketLocationResponse;
        deleteBasketLocations(request: dev.docuware.com.services.settings.DeleteBasketLocations ): dev.docuware.com.services.settings.DeleteBasketLocationsResponse;
        getWebBaskets(request: dev.docuware.com.services.settings.GetWebBaskets ): dev.docuware.com.services.settings.GetWebBasketsResponse;
        saveWebBasket(request: dev.docuware.com.services.settings.SaveWebBasket ): dev.docuware.com.services.settings.SaveWebBasketResponse;
        deleteWebBaskets(request: dev.docuware.com.services.settings.DeleteWebBaskets ): dev.docuware.com.services.settings.DeleteWebBasketsResponse;
        getRules(request: dev.docuware.com.services.settings.GetRules ): dev.docuware.com.services.settings.GetRulesResponse;
        saveRule(request: dev.docuware.com.services.settings.SaveRule): dev.docuware.com.services.settings.SaveRuleResponse;
        deleteRules(request: dev.docuware.com.services.settings.DeleteRules ): dev.docuware.com.services.settings.DeleteRulesResponse;
        getNotificationSettings(request: dev.docuware.com.services.settings.GetNotificationSettings ): dev.docuware.com.services.settings.GetNotificationSettingsResponse;
        saveNotificationSetting(request: dev.docuware.com.services.settings.SaveNotificationSetting ): dev.docuware.com.services.settings.SaveNotificationSettingResponse;
        deleteNotificationSettings(request: dev.docuware.com.services.settings.DeleteNotificationSettings ): dev.docuware.com.services.settings.DeleteNotificationSettingsResponse;
        getOCRHeaders(request: dev.docuware.com.services.settings.GetOCRHeaders): dev.docuware.com.services.settings.GetOCRHeadersResponse;
        getOCRTemplates(request: dev.docuware.com.services.settings.GetOCRTemplates ): dev.docuware.com.services.settings.GetOCRTemplatesResponse;
        saveOCRTemplate(request: dev.docuware.com.services.settings.SaveOCRTemplate ): dev.docuware.com.services.settings.SaveOCRTemplateResponse;
        deleteOCRTemplates(request: dev.docuware.com.services.settings.DeleteOCRTemplates ): dev.docuware.com.services.settings.DeleteOCRTemplatesResponse;
        getOBRHeaders(request: dev.docuware.com.services.settings.GetOBRHeaders ): dev.docuware.com.services.settings.GetOBRHeadersResponse;
        getOBRConfigs(request: dev.docuware.com.services.settings.GetOBRConfigs ): dev.docuware.com.services.settings.GetOBRConfigsResponse;
        saveOBRConfig(request: dev.docuware.com.services.settings.SaveOBRConfig ): dev.docuware.com.services.settings.SaveOBRConfigResponse;
        deleteOBRConfigs(request: dev.docuware.com.services.settings.DeleteOBRConfigs ): dev.docuware.com.services.settings.DeleteOBRConfigsResponse;
        getOptRecHeaders(request: dev.docuware.com.services.settings.GetOptRecHeaders ): dev.docuware.com.services.settings.GetOptRecHeadersResponse;
        hasRight(request: dev.docuware.com.services.settings.HasRight ): dev.docuware.com.services.settings.HasRightResponse;
        hasFileCabinetRight(request: dev.docuware.com.services.settings.HasFileCabinetRight ): dev.docuware.com.services.settings.HasFileCabinetRightResponse;
        getFunctionalRights(request: dev.docuware.com.services.settings.GetFunctionalRights): dev.docuware.com.services.settings.GetFunctionalRightsResponse;
        assignFunctionalRights(request: dev.docuware.com.services.settings.AssignFunctionalRights): dev.docuware.com.services.settings.AssignFunctionalRightsResponse;
        hasLicenseInstalled(request: dev.docuware.com.services.settings.HasLicenseInstalled): dev.docuware.com.services.settings.HasLicenseInstalledResponse;
        hasActiveLicense(request: dev.docuware.com.services.settings.HasActiveLicense ): dev.docuware.com.services.settings.HasActiveLicenseResponse;
        getSystemStoragePath(request: dev.docuware.com.services.settings.GetSystemStoragePath ): dev.docuware.com.services.settings.GetSystemStoragePathResponse;
        updateLicense(request: dev.docuware.com.services.settings.UpdateLicense ): dev.docuware.com.services.settings.UpdateLicenseResponse;
        assignNamedLicenses(request: dev.docuware.com.services.settings.AssignNamedLicenses ): dev.docuware.com.services.settings.AssignNamedLicensesResponse;
        removeUsersFromLicenses(request: dev.docuware.com.services.settings.RemoveUsersFromLicensesRequest): dev.docuware.com.services.settings.RemoveUsersFromLicensesResponse;
        assignUsersToLicenses(request: dev.docuware.com.services.settings.AssignUsersToLicensesRequest): dev.docuware.com.services.settings.AssignUsersToLicensesResponse;
        freeNamedLicenses(request: dev.docuware.com.services.settings.FreeNamedLicenses): dev.docuware.com.services.settings.FreeNamedLicensesResponse;
        getLicenses(request: dev.docuware.com.services.settings.GetLicenses ): dev.docuware.com.services.settings.GetLicensesResponse;
        hasAdminRight(request: dev.docuware.com.services.settings.HasAdminRight ): dev.docuware.com.services.settings.HasAdminRightResponse;
        hasUsageRight(request: dev.docuware.com.services.settings.HasUsageRight ): dev.docuware.com.services.settings.HasUsageRightResponse;
        lockSettings(request: dev.docuware.com.services.settings.LockSettings ): dev.docuware.com.services.settings.LockSettingsResponse;
        clearLock(request: dev.docuware.com.services.settings.ClearLock ): dev.docuware.com.services.settings.ClearLockResponse;
        clearLocks(request: dev.docuware.com.services.settings.ClearLocks ): dev.docuware.com.services.settings.ClearLocksResponse;
        isOnlineInstallation(request: dev.docuware.com.services.settings.IsOnlineInstallation ): dev.docuware.com.services.settings.IsOnlineInstallationResponse;
        isBusinessInstallation(request: dev.docuware.com.services.settings.IsBusinessInstallation ): dev.docuware.com.services.settings.IsBusinessInstallationResponse;
        isFreeSQLOrganization(request: dev.docuware.com.services.settings.IsFreeSQLOrganization ): dev.docuware.com.services.settings.IsFreeSQLOrganizationResponse;
        existResourceRelation(request: dev.docuware.com.services.settings.ExistResourceRelation ): dev.docuware.com.services.settings.ExistResourceRelationResponse;
        addResourceRelations(request: dev.docuware.com.services.settings.AddResourceRelations ): dev.docuware.com.services.settings.AddResourceRelationsResponse;
        removeResourceRelations(request: dev.docuware.com.services.settings.RemoveResourceRelations ): dev.docuware.com.services.settings.RemoveResourceRelationsResponse;
        getResourceRelations(request: dev.docuware.com.services.settings.GetResourceRelations ): dev.docuware.com.services.settings.GetResourceRelationsResponse;
        replaceResourceRelations(request: dev.docuware.com.services.settings.ReplaceResourceRelations ): dev.docuware.com.services.settings.ReplaceResourceRelationsResponse;
        getOutlookConfigurationHeaders(request: dev.docuware.com.services.settings.GetOutlookConfigurationHeaders ): dev.docuware.com.services.settings.GetOutlookConfigurationHeadersResponse;
        getOutlookConfigurations(request: dev.docuware.com.services.settings.GetOutlookConfigurations ): dev.docuware.com.services.settings.GetOutlookConfigurationsResponse;
        saveOutlookConfiguration(request: dev.docuware.com.services.settings.SaveOutlookConfiguration ): dev.docuware.com.services.settings.SaveOutlookConfigurationResponse;
        deleteOutlookConfigurations(request: dev.docuware.com.services.settings.DeleteOutlookConfigurations ): dev.docuware.com.services.settings.DeleteOutlookConfigurationsResponse;
        getOutlookAccessHeaders(request: dev.docuware.com.services.settings.GetOutlookAccessHeaders ): dev.docuware.com.services.settings.GetOutlookAccessHeadersResponse;
        getOutlookAccessSettings(request: dev.docuware.com.services.settings.GetOutlookAccessSettings ): dev.docuware.com.services.settings.GetOutlookAccessSettingsResponse;
        saveOutlookAccessSetting(request: dev.docuware.com.services.settings.SaveOutlookAccessSetting ): dev.docuware.com.services.settings.SaveOutlookAccessSettingResponse;
        deleteOutlookAccessSettings(request: dev.docuware.com.services.settings.DeleteOutlookAccessSettings ): dev.docuware.com.services.settings.DeleteOutlookAccessSettingsResponse;
        getPrinterConfigurationHeaders(request: dev.docuware.com.services.settings.GetPrinterConfigurationHeaders ): dev.docuware.com.services.settings.GetPrinterConfigurationHeadersResponse;
        getPrinterConfigurations(request: dev.docuware.com.services.settings.GetPrinterConfigurations ): dev.docuware.com.services.settings.GetPrinterConfigurationsResponse;
        savePrinterConfiguration(request: dev.docuware.com.services.settings.SavePrinterConfiguration ): dev.docuware.com.services.settings.SavePrinterConfigurationResponse;
        deletePrinterConfigurations(request: dev.docuware.com.services.settings.DeletePrinterConfigurations ): dev.docuware.com.services.settings.DeletePrinterConfigurationsResponse;
        getProcessDefinitions(request: dev.docuware.com.services.settings.GetProcessDefinitions ): dev.docuware.com.services.settings.GetProcessDefinitionsResponse;
        getImportConfigurationHeaders(request: dev.docuware.com.services.settings.GetImportConfigurationHeaders ): dev.docuware.com.services.settings.GetImportConfigurationHeadersResponse;
        getImportConfigurations(request: dev.docuware.com.services.settings.GetImportConfigurations ): dev.docuware.com.services.settings.GetImportConfigurationsResponse;
        saveImportConfiguration(request: dev.docuware.com.services.settings.SaveImportConfiguration ): dev.docuware.com.services.settings.SaveImportConfigurationResponse;
        deleteImportConfigurations(request: dev.docuware.com.services.settings.DeleteImportConfigurations ): dev.docuware.com.services.settings.DeleteImportConfigurationsResponse;
        getImapConnectionHeaders(request: dev.docuware.com.services.settings.GetImapConnectionHeaders ): dev.docuware.com.services.settings.GetImapConnectionHeadersResponse;
        getImapConnections(request: dev.docuware.com.services.settings.GetImapConnections ): dev.docuware.com.services.settings.GetImapConnectionsResponse;
        saveImapConnection(request: dev.docuware.com.services.settings.SaveImapConnection ): dev.docuware.com.services.settings.SaveImapConnectionResponse;
        deleteImapConnections(request: dev.docuware.com.services.settings.DeleteImapConnections ): dev.docuware.com.services.settings.DeleteImapConnectionsResponse;
        getImapServers(request: dev.docuware.com.services.settings.GetImapServers ): dev.docuware.com.services.settings.GetImapServersResponse;
        saveIMAPServer(request: dev.docuware.com.services.settings.SaveIMAPServer ): dev.docuware.com.services.settings.SaveIMAPServerResponse;
        deleteIMAPServers(request: dev.docuware.com.services.settings.DeleteIMAPServers ): dev.docuware.com.services.settings.DeleteIMAPServersResponse;
        getMailServiceHeaders(request: dev.docuware.com.services.settings.GetMailServiceHeaders): dev.docuware.com.services.settings.GetMailServiceHeadersResponse;
        getMailServices(request: dev.docuware.com.services.settings.GetMailServices): dev.docuware.com.services.settings.GetMailServicesResponse;
        saveMailService(request: dev.docuware.com.services.settings.SaveMailService): dev.docuware.com.services.settings.SaveMailServiceResponse;
        deleteMailServices(request: dev.docuware.com.services.settings.DeleteMailServices): dev.docuware.com.services.settings.DeleteMailServicesResponse;
        getFormHeaders(request: dev.docuware.com.services.forms.GetFormHeaders): dev.docuware.com.services.forms.GetFormHeadersResponse;
        getFormConfigurations(request: dev.docuware.com.services.forms.GetFormConfigurations): dev.docuware.com.services.forms.GetFormConfigurationsResponse;
        saveFormConfiguration(request: dev.docuware.com.services.forms.SaveFormConfiguration): dev.docuware.com.services.forms.SaveFormConfigurationResponse;
        deleteFormConfigurations(request: dev.docuware.com.services.forms.DeleteFormConfigurations): dev.docuware.com.services.forms.DeleteFormConfigurationsResponse;
        getReplicationHeaders(request: dev.docuware.com.services.settings.GetReplicationHeaders ): dev.docuware.com.services.settings.GetReplicationHeadersResponse;
        getReplications(request: dev.docuware.com.services.settings.GetReplications ): dev.docuware.com.services.settings.GetReplicationsResponse;
        saveReplication(request: dev.docuware.com.services.settings.SaveReplication ): dev.docuware.com.services.settings.SaveReplicationResponse;
        deleteReplications(request: dev.docuware.com.services.settings.DeleteReplications ): dev.docuware.com.services.settings.DeleteReplicationsResponse;
        getAutoIndexHeaders(request: dev.docuware.com.services.settings.GetAutoIndexHeaders ): dev.docuware.com.services.settings.GetAutoIndexHeadersResponse;
        getAutoIndexes(request: dev.docuware.com.services.settings.GetAutoIndexes): dev.docuware.com.services.settings.GetAutoIndexesResponse;
        saveAutoIndex(request: dev.docuware.com.services.settings.SaveAutoIndex): dev.docuware.com.services.settings.SaveAutoIndexResponse;
        deleteAutoIndexes(request: dev.docuware.com.services.settings.DeleteAutoIndexes): dev.docuware.com.services.settings.DeleteAutoIndexesResponse;
        getScheduleSettings(request: dev.docuware.com.services.settings.GetScheduleSettings): dev.docuware.com.services.settings.GetScheduleSettingsResponse;
        saveScheduleSettings(request: dev.docuware.com.services.settings.SaveScheduleSettings): dev.docuware.com.services.settings.SaveScheduleSettingsResponse;
        deleteScheduleSettings(request: dev.docuware.com.services.settings.DeleteScheduleSettings): dev.docuware.com.services.settings.DeleteScheduleSettingsResponse;
        getBusinessUseCaseHistory(request: dev.docuware.com.services.settings.GetBusinessUseCaseHistory): dev.docuware.com.services.settings.GetBusinessUseCaseHistoryResponse;
    }
}